import coin1 from "./asset/coin1.jpg";
import coin2 from "./asset/coin2.jpg";
import coin3 from "./asset/coin3.jpg";
import coin4 from "./asset/coin4.jpg";
import coin5 from "./asset/coin5.jpg";
export const data = [
  {
    id: 1,
    name: "Yachi Club",
    image: coin1,
    category: "Collectibles",
    balance: "$134.36",
    upper: "3.08",
    bottom: "23.90",
    brandname: "Tron",
    red: "red",
  },
  {
    id: 2,
    name: "Uniswap",
    image: coin2,
    category: "Exchanges",
    balance: "$122.40",
    upper: "10.89",
    bottom: "42.90",
    brandname: "ETH",
  },
  {
    id: 3,
    name: "QuickSwap",
    image: coin3,
    category: "Exchanges",
    balance: "$12.20",
    upper: "10.9",
    bottom: "30.90",
    brandname: "Polygon",
    red: "red",

  },
  {
    id: 4,
    name: "Trader Jos",
    image: coin3,
    category: "Exchanges",
    balance: "$12.20",
    upper: "10.9",
    bottom: "30.90",
    brandname: "AVALANCHE",
    red: "red",

  },
  {
    id: 5,
    name: "JustSwap",
    image: coin4,
    category: "Exchanges",
    balance: "$8.20",
    upper: "58.9",
    bottom: "20.90",
    brandname: "WAX",
  },
  {
    id: 6,
    name: "Al-exchange",
    image: coin5,
    category: "Exchanges",
    balance: "$8.50",
    upper: "48.9",
    bottom: "10.90",
    brandname: "IOTEX",
  },
  {
    id: 7,
    name: "Bored Ape",
    image: coin1,
    category: "Collectibles",
    balance: "$134.36",
    upper: "3.08",
    bottom: "23.90",
    brandname: "Tron",
    red: "red",

  },
  {
    id: 8,
    name: "Uniswap",
    image: coin2,
    category: "Exchanges",
    balance: "$122.40",
    upper: "10.89",
    bottom: "42.90",
    brandname: "Tron",
  },
  {
    id: 9,
    name: "QuickSwap",
    image: coin3,
    category: "Exchanges",
    balance: "$12.20",
    upper: "10.9",
    bottom: "30.90",
    brandname: "BSC",
  },
  {
    id: 10,
    name: "Trader Jos",
    image: coin3,
    category: "Exchanges",
    balance: "$12.20",
    upper: "10.9",
    bottom: "30.90",
    brandname: "BSC",
    red: "red",

  },
  {
    id: 11,
    name: "JustSwap",
    image: coin4,
    category: "Exchanges",
    balance: "$8.20",
    upper: "58.9",
    bottom: "20.90",
    brandname: "Polygon",
  },
  {
    id: 12,
    name: "MimoSwapv2",
    image: coin5,
    category: "Exchanges",
    balance: "$8.50",
    upper: "48.9",
    bottom: "10.90",
    brandname: "BSC",
    red: "red",

  },
  {
    id: 13,
    name: "Al-exchange",
    image: coin5,
    category: "Exchanges",
    balance: "$8.50",
    upper: "48.9",
    bottom: "10.90",
    brandname: "IOTEX",
  },
  {
    id: 14,
    name: "Bored ",
    image: coin1,
    category: "Collectibles",
    balance: "$134.36",
    upper: "3.08",
    bottom: "23.90",
    brandname: "Tron",
    red: "red",

  },
  {
    id: 15,
    name: "Uniswap",
    image: coin2,
    category: "Exchanges",
    balance: "$122.40",
    upper: "10.89",
    bottom: "42.90",
    brandname: "Tron",
  },
  {
    id: 16,
    name: "QuickSwap",
    image: coin3,
    category: "Exchanges",
    balance: "$12.20",
    upper: "10.9",
    bottom: "30.90",
    brandname: "BSC",
  },
  {
    id: 17,
    name: "Trader Jos",
    image: coin3,
    category: "Exchanges",
    balance: "$12.20",
    upper: "10.9",
    bottom: "30.90",
    brandname: "BSC",
    red: "red",

  },
  {
    id: 18,
    name: "JustSwap",
    image: coin4,
    category: "Exchanges",
    balance: "$8.20",
    upper: "58.9",
    bottom: "20.90",
    brandname: "Polygon",
  },
  {
    id: 19,
    name: "MimoSwapv2",
    image: coin5,
    category: "Exchanges",
    balance: "$8.50",
    upper: "48.9",
    bottom: "10.90",
    brandname: "BSC",
    red: "red",

  },
];
